//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appeal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Appeal()
        {
            this.Response_to_the_appeal = new HashSet<Response_to_the_appeal>();
            this.Description_appeal = new HashSet<Description_appeal>();
        }
    
        public int ID { get; set; }
        public int status { get; set; }
        public int applicant { get; set; }
        public int problem_type { get; set; }
        public System.DateTime date { get; set; }
        public int order { get; set; }
        public int importance { get; set; }
        public string description { get; set; }
        public int id_user { get; set; }
    
        public virtual Applicant Applicant1 { get; set; }
        public virtual Importance Importance1 { get; set; }
        public virtual Order Order1 { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Type_problem Type_problem { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Response_to_the_appeal> Response_to_the_appeal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Description_appeal> Description_appeal { get; set; }
    }
}
