//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blocking_the_driver
    {
        public int id { get; set; }
        public int id_driver { get; set; }
        public int id_user { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual User User { get; set; }
    }
}
