//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int id { get; set; }
        public string description { get; set; }
        public int id_type_sender { get; set; }
        public System.DateTime time { get; set; }
        public int id_order { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Type_Sender Type_Sender { get; set; }
    }
}
