//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSupport
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appeal> Appeal { get; set; }
        public virtual DbSet<Applicant> Applicant { get; set; }
        public virtual DbSet<Description_appeal> Description_appeal { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<FAQ> FAQ { get; set; }
        public virtual DbSet<Importance> Importance { get; set; }
        public virtual DbSet<Judgment> Judgment { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Order_status> Order_status { get; set; }
        public virtual DbSet<PayType> PayType { get; set; }
        public virtual DbSet<Post> Post { get; set; }
        public virtual DbSet<Response_to_the_appeal> Response_to_the_appeal { get; set; }
        public virtual DbSet<Status_of_the_driver_s_account> Status_of_the_driver_s_account { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Tariff> Tariff { get; set; }
        public virtual DbSet<Tariff_zone> Tariff_zone { get; set; }
        public virtual DbSet<Type_problem> Type_problem { get; set; }
        public virtual DbSet<Type_Sender> Type_Sender { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Blocking_the_driver> Blocking_the_driver { get; set; }
    }
}
