//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Appeal = new HashSet<Appeal>();
            this.Message = new HashSet<Message>();
            this.Options = new HashSet<Options>();
        }
    
        public int id { get; set; }
        public string starting_point { get; set; }
        public string end_point { get; set; }
        public string customer_name { get; set; }
        public string customer_phone { get; set; }
        public decimal price { get; set; }
        public int driver { get; set; }
        public System.DateTime time { get; set; }
        public int tariff { get; set; }
        public string description { get; set; }
        public string number { get; set; }
        public int status { get; set; }
        public int id_paytype { get; set; }
        public string driver_point { get; set; }
        public decimal mileage { get; set; }
        public int tariff_zone { get; set; }
        public int loyalty_for_the_order { get; set; }
        public string travel_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appeal> Appeal { get; set; }
        public virtual Driver Driver1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message> Message { get; set; }
        public virtual Order_status Order_status { get; set; }
        public virtual PayType PayType { get; set; }
        public virtual Tariff Tariff1 { get; set; }
        public virtual Tariff_zone Tariff_zone1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Options> Options { get; set; }
    }
}
