//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxiSupport
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response_to_the_appeal
    {
        public int id { get; set; }
        public int id_user { get; set; }
        public string responce { get; set; }
        public int id_appeal { get; set; }
        public System.DateTime date { get; set; }
        public int id_judgment { get; set; }
    
        public virtual Appeal Appeal { get; set; }
        public virtual Judgment Judgment { get; set; }
        public virtual User User { get; set; }
    }
}
